CREATE TABLE MY_USER (
  id NUMBER(19)  PRIMARY KEY,
  name VARCHAR2(250) NOT NULL,
  surname VARCHAR2(250) NOT NULL,
  address VARCHAR2(250) DEFAULT NULL
);

CREATE SEQUENCE MY_USER_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER USER_seq_tr
 BEFORE INSERT ON MY_USER FOR EACH ROW
 WHEN (NEW.id IS NULL)
BEGIN
 SELECT MY_USER_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/


CREATE TABLE SHEDLOCK (
  name VARCHAR2(64),
  lock_until TIMESTAMP(3) NULL,
  locked_at TIMESTAMP(3) NULL,
  locked_by VARCHAR2(255),
  PRIMARY KEY (name)
);